src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dev Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Head Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resources Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RankingController.cls
public class RankingController {
     public List<RankingWrapper> people {get;set;} 
    public Integer offsetSize = 0;
    public String role {get;set;} 
    public String seniority {get;set;} 
    public String showHideTable {get;set;}
    
    public RankingController(){
        people = new List<RankingWrapper>();
        showHideTable = 'display: none';
    }
    
    public void searchPeopleForRanking(){
        system.debug('searchPeopleForRanking');
        people = JSUtils.searchRanking(role, seniority);
        showHideTable = 'display: inline';
    }
    
    public Boolean getEmpty() { 
        return people.size() == 0;
    }
    
    public List<SelectOption> getRoleItems() {
        List<SelectOption> options = new List<SelectOption>();
        List<String> optionsString = new List<String>();
        AggregateResult[] roles = [SELECT Role__c 
                                   FROM Employee__c 
                                   GROUP BY Role__c];
        for (AggregateResult ar : roles)  {
            if(ar.get('Role__c') != null){
                options.add(new SelectOption(ar.get('Role__c')+'',ar.get('Role__c')+''));
                optionsString.add(ar.get('Role__c')+'');
            }
        }
        AggregateResult[] rolesCandidate = [SELECT Role__c 
                                            FROM Candidate__c
                                            WHERE Role__c NOT IN :optionsString
                                            GROUP BY Role__c];
        for (AggregateResult ar : rolesCandidate)  {
            if(ar.get('Role__c') != null){
                options.add(new SelectOption(ar.get('Role__c')+'',ar.get('Role__c')+''));
            }
        }
        return options;
    }
    
    public List<SelectOption> getSeniorityItems() {
        List<SelectOption> options = new List<SelectOption>();
        List<String> optionsString = new List<String>();
        AggregateResult[] seniorities = [SELECT Seniority__c 
                                         FROM Employee__c 
                                         GROUP BY Seniority__c];
        for (AggregateResult ar : seniorities)  {
            if(ar.get('Seniority__c') != null){
                options.add(new SelectOption(ar.get('Seniority__c')+'',ar.get('Seniority__c')+''));
                optionsString.add(ar.get('Seniority__c')+'');
            }
        }
        AggregateResult[] senioritiesCandidate = [SELECT Seniority__c 
                                            FROM Candidate__c
                                            WHERE Seniority__c NOT IN :optionsString
                                            GROUP BY Seniority__c];
        for (AggregateResult ar : senioritiesCandidate)  {
            if(ar.get('Seniority__c') != null){
                options.add(new SelectOption(ar.get('Seniority__c')+'',ar.get('Seniority__c')+''));
            }
        }
        
        return options;
    }

}