src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Workplace__c</fullName>
        <label>Actual Workplace</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dev Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CompanyStartDate__c</fullName>
        <label>Company Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DepartureDate__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DepartureReason__c</fullName>
        <label>Departure Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Quit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fired</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Torre 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Torre 2</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Head Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resources Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change: Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change: Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Employee</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Team</relationshipLabel>
        <relationshipName>Project_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{000000}</displayFormat>
        <label>PTM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmployeeControllerTest.cls
@isTest
public class EmployeeControllerTest {

    @testSetup
    static void setupData(){
        Employee__c e = new Employee__c();
        e.Name = 'Test Tester';
        e.CI__c = 00000000;
        e.Role__c = 'Developer';
        e.Skills__c = 'Test Skills';
        insert e;
        
        Project__c p = new Project__c();
        p.Name = 'Test Project';
        p.Client__c = 'Test Client';
        insert p;
        
        Project__c p2 = new Project__c();
        p2.Name = 'Test Project 2';
        p2.Client__c = 'Test Client 2';
        insert p2;
        
        Project_Team_Member__c ptm = new Project_Team_Member__c();
        ptm.Employee__c = e.Id;
        ptm.Project__c = p.Id;
        ptm.Role__c = 'Developer';
        insert ptm;
        
        Candidate__c c = new Candidate__c();
        c.Actual_Workplace__c = 'Test';
        c.CI__c = 11111111;
        c.Name = 'Test Candidate';
        c.Role__c = 'Developer';
        c.Seniority__c = 'Junior';
        c.Skills__c = 'Test Skills';
        insert c;
    }
    
    @isTest
    static void terminateEmployeeFired(){
        Employee__c emp = [SELECT Id FROM Employee__c WHERE Name = 'Test Tester'];
        Id empId = emp.Id;
        
       	Test.startTest();
        EmployeeController.updateTerminateEmployee(empId, 'Fired');
        Test.stopTest();
        
        Employee__c employee = [SELECT Id, DepartureDate__c, DepartureReason__c, Name, Status__c FROM Employee__c WHERE Id =: empId];
        
        System.assertEquals(Date.Today(), employee.DepartureDate__c);
        System.assertEquals('Fired', employee.DepartureReason__c);
        System.assertEquals('Test Tester (Former Employee)', employee.Name);
        System.assertEquals('Former Employee', employee.Status__c);
        
    }
    
    @isTest
    static void terminateEmployeeQuit(){
        Employee__c emp = [SELECT Id FROM Employee__c WHERE Name = 'Test Tester'];
        Id empId = emp.Id;
        
       	Test.startTest();
        EmployeeController.updateTerminateEmployee(empId, 'Quit');
        Test.stopTest();
        
        Employee__c employee = [SELECT Id, DepartureDate__c, DepartureReason__c, Name, Status__c FROM Employee__c WHERE Id =: empId];
        
        List<Project_Team_Member__c> ptms = [SELECT Id FROM Project_Team_Member__c WHERE Employee__c =: empId];
        
        System.assertEquals(Date.Today(), employee.DepartureDate__c);
        System.assertEquals('Quit', employee.DepartureReason__c);
        System.assertEquals('Test Tester (Former Employee)', employee.Name);
        System.assertEquals('Former Employee', employee.Status__c);
        System.assertEquals(0, ptms.size());
        
    }
    
    @isTest
    static void testConvertCandidateToEmployeeNoProject(){
        Candidate__c c = [SELECT Id, Name, Actual_Workplace__c, Role__c, Seniority__c FROM Candidate__c WHERE Name = 'Test Candidate'];
        
        String startDate = '2018-02-02';
        String location = 'Torre 1';
        String status = 'Bench';
        String project = null;
        
        Test.startTest();
        Integer returnFromServer = EmployeeController.convertCandidateToEmployee(c.Id, startDate, location, status, project);
        Test.stopTest();
        
        Employee__c newEmp = [SELECT Id, Name, CI__c, Role__c, Seniority__c, Location__c, CompanyStartDate__c, Status__c FROM Employee__c WHERE Name = 'Test Candidate'];
        Candidate__c updatedCand = [SELECT Name, Actual_Workplace__c FROM Candidate__c WHERE Name LIKE 'Test Candidate%'];
        
        System.assertEquals(0, returnFromServer);
        System.assertEquals('Test Candidate', newEmp.Name);
        System.assertEquals(11111111, newEmp.CI__c);
        System.assertEquals('Developer', newEmp.Role__c);
        System.assertEquals('Junior', newEmp.Seniority__c);
        System.assertEquals('Torre 1', newEmp.Location__c);
        System.assertEquals('Bench', newEmp.Status__c);
        System.assertEquals(Date.valueOf('2018-02-02'), newEmp.CompanyStartDate__c);
        System.assertEquals('Test Candidate - (Converted to Employee)', updatedCand.Name);
        System.assertEquals('Altimetrik', updatedCand.Actual_Workplace__c);
        
    }
    
    @isTest
    static void testConvertCandidateToEmployeeErrorTwo(){
        Candidate__c c = [SELECT Id, Name, Actual_Workplace__c, Role__c, Seniority__c FROM Candidate__c WHERE Name = 'Test Candidate'];
        c.Name += ' - (Converted to Employee)';
        update c;
        
        String startDate = '2018-02-02';
        String location = 'Torre 1';
        String status = 'Bench';
        String project = null;
        
        Test.startTest();
        Integer returnFromServer = EmployeeController.convertCandidateToEmployee(c.Id, startDate, location, status, project);
        Test.stopTest();
        
        System.assertEquals(2, returnFromServer);
    }
    
    @isTest
    static void testConvertCandidateToEmployeeWithProject(){
        Candidate__c c = [SELECT Id, Name, Actual_Workplace__c, Role__c, Seniority__c FROM Candidate__c WHERE Name = 'Test Candidate'];
        Project__c p = [SELECT Id, Name FROM Project__c WHERE Name = 'Test Project'];
        
        String startDate = '2018-02-02';
        String location = 'Torre 1';
        String status = 'Project';
        String project = 'Test Project';
        
        Test.startTest();
        Integer returnFromServer = EmployeeController.convertCandidateToEmployee(c.Id, startDate, location, status, project);
        Test.stopTest();
        
        Employee__c newEmp = [SELECT Id, Name, CI__c, Role__c, Seniority__c, Location__c, CompanyStartDate__c, Status__c FROM Employee__c WHERE Name = 'Test Candidate'];
        Candidate__c updatedCand = [SELECT Name, Actual_Workplace__c FROM Candidate__c WHERE Name LIKE 'Test Candidate%'];
        Project_Team_Member__c ptm = [SELECT Id, Project__c, Employee__c FROM Project_Team_Member__C WHERE Employee__c =: newEmp.Id];
        
        System.assertEquals(0, returnFromServer);
        System.assertEquals('Test Candidate', newEmp.Name);
        System.assertEquals(11111111, newEmp.CI__c);
        System.assertEquals('Developer', newEmp.Role__c);
        System.assertEquals('Junior', newEmp.Seniority__c);
        System.assertEquals('Torre 1', newEmp.Location__c);
        System.assertEquals('Project', newEmp.Status__c);
        System.assertEquals(Date.valueOf('2018-02-02'), newEmp.CompanyStartDate__c);
        System.assertEquals('Test Candidate - (Converted to Employee)', updatedCand.Name);
        System.assertEquals('Altimetrik', updatedCand.Actual_Workplace__c);
        System.assertEquals(p.Id, ptm.Project__c);
        System.assertEquals(newEmp.Id, ptm.Employee__c);
        
    }
    
    @isTest
    static void testGetProjects(){
        Test.startTest();
        List<Project__c> projects = EmployeeController.getProjects();
        Test.stopTest();
        
        System.assertEquals('Test Project', projects[0].Name);
        System.assertEquals('Test Project 2', projects[1].Name);
        
    }
}