src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dev Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CompanyStartDate__c</fullName>
        <label>Company Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Imagen__c</fullName>
        <label>Imagen</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Head Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resources Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change: Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change: Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Employee</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Option__c.object
<CustomObject>
    <fields>
        <fullName>Option_Text__c</fullName>
        <label>Option Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Techincal_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Question</label>
        <referenceTo>Technical_Question__c</referenceTo>
        <relationshipLabel>Option</relationshipLabel>
        <relationshipName>Option</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>anwser__c</fullName>
        <label>Answer</label>
        <picklist>
            <picklistValues>
                <fullName>Correct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Option</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Technology__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technology</label>
        <referenceTo>Technology__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Technical_Question__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Head Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resources Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Technical_Question_Text__c</fullName>
        <label>Technical Question Text</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Technology__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technology</label>
        <referenceTo>Technology__c</referenceTo>
        <relationshipLabel>Technical Questions</relationshipLabel>
        <relationshipName>Technical_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Technical Question</label>
    <nameField>
        <displayFormat>TQ-{0000}</displayFormat>
        <label>Technical Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technical Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Technical_Test__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Technical Tests</relationshipLabel>
        <relationshipName>Technical_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Techincal_Question__c</fullName>
        <label>Techincal Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technology__c</fullName>
        <label>Technology</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Technical Test</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Technical Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technical Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Technology__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Technologies</relationshipLabel>
        <relationshipName>Technologies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JSUtils.cls
public class JSUtils {
    
    public static Integer DEFAULT_PAGE_SIZE = 10;
    public static Integer DEFAULT_PAGE_SIZE_RANKING = 50;
    public static Integer NUMBER_OF_QUESTIONS = 10;
    
    public static List<Project__c> getProjects(){
        return [SELECT Id, Name FROM Project__c 
                WHERE Active__c = true
                LIMIT 100];
    }

    
    public static List<Employee__c> getEmployees(String role){
        return [SELECT Id, Name, Imagen__c FROM Employee__c 
                WHERE Role__c = :role
                AND Status__c != 'Former Employee'
                LIMIT 10];
    }
    
    public static List<Employee__c> getEmployee(Integer ci){
        List<Employee__c> emp = new List<Employee__c>();
        emp = [SELECT Id, Name, Address__c, CI__c, CompanyStartDate__c  FROM Employee__c 
                WHERE CI__c = :ci
                LIMIT 1];
        return emp;
    }
    
    public static List<Candidate__c> getCandidate(Integer ci){
        return [SELECT Id, Name FROM Candidate__c 
                WHERE CI__c = :ci
                LIMIT 1];
    }
    
    public static Boolean checkIfContainsNumber(List<Integer> listNumbers, Integer numberToCheck){
        Boolean containNumber = false;
        for(Integer numberFromList : listNumbers){
            if(numberToCheck == numberFromList){
                containNumber = true;
            }
        }
        system.debug('containNumber: ' + containNumber);
        return containNumber;
    }
    
    public static List<Option__c> getOpciones(String technicalQuestionId){
        return [SELECT Id, Option_Text__c, anwser__c FROM Option__c 
                WHERE Techincal_Question__r.Id = :technicalQuestionId
                ORDER BY Option_Text__c
                LIMIT 1000];
    }
    
    public static List<Technical_Question__c> getTechnicalQuestions(String Technology, String Seniority, String Role){
        List<Technical_Question__c> questionsForTest = new List<Technical_Question__c>(); 
        List<Technical_Question__c> questions = [SELECT Id, Name, Technical_Question_Text__c FROM Technical_Question__c 
                                                 WHERE Seniority__c = :Seniority
                                                 AND Role__c = :Role
                                                 AND Technology__r.Name = :Technology LIMIT 1000];
        
        
        if(questions.size() > 0){
            
            List<Integer> randomNumbers = new List<Integer>();
            Integer numbersRandoms = 1;
            do {
                Double random = Math.floor(Math.random() * questions.size() + 1);
                Integer randomIn = random.intValue();
                system.debug('randomIn: ' + randomIn);
                if(!checkIfContainsNumber(randomNumbers, randomIn)){
                    randomNumbers.add(randomIn);
                    questionsForTest.add(questions.get(randomIn - 1));
                    numbersRandoms++;
                }
            } while (numbersRandoms <= NUMBER_OF_QUESTIONS);
            
        }
        return questionsForTest;
    }
    
    public static List<Employee__c> searchSkill(String skill, Integer limitSize, Integer offsetSize){
        String skillToSearch = '%' + skill + '%';
        return [SELECT Id, Name, Skills__c, Role__c, Location__c, Status__c FROM 
                Employee__c 
                WHERE Skills__c  LIKE :skillToSearch
                AND Status__c != 'Former Employee'
                LIMIT :limitSize
                OFFSET :offsetSize];
    }
    
    public static List<RankingWrapper> searchRanking(String role, String seniority){
        
        List<RankingWrapper> peopleRanked = new List<RankingWrapper>();
        List<RankingWrapper> auxPeopleRanked = new List<RankingWrapper>();
        
        List<Employee__c> employees = [SELECT Id, Name, Role__c, Seniority__c FROM Employee__c 
                                       WHERE (Status__c = 'Change: Role' OR  Status__c = 'Change: Project')
                                       AND Role_Change__c = :role
                                       LIMIT 1000]; 
        if(employees.size() > 0){
            for(Employee__c emp : employees){
                Decimal rankingNumberEmp = 0;
                String colorEmp = 'orange';
                peopleRanked.add(new RankingWrapper(emp.Name, emp.Id, emp.Role__c, emp.Seniority__c, colorEmp, rankingNumberEmp));
            }
        }
        if(peopleRanked.size() < DEFAULT_PAGE_SIZE_RANKING){
            for(Candidate__c candidate : [SELECT Id, Name, Role__c, Seniority__c, Skills__c FROM Candidate__c 
                                          WHERE Role__c = :role 
                                          AND Seniority__c = :seniority
                                          AND Actual_Workplace__c != 'Altimetrik'
                                          LIMIT 1000]){
                                              Decimal result = 0;
                                              Integer numberOfTest = 0;
                                              Decimal rankingNumber = 0;
                                              String color = 'black';
                                              for(Technical_Test__c test : [SELECT Id, Result__c FROM Technical_Test__c 
                                                                            WHERE Candidate__c = :candidate.Id LIMIT 1000] ){
                                                                                result = result + test.Result__c;
                                                                                numberOfTest++;
                                                                            }
                                              if(numberOfTest > 0){
                                                  rankingNumber = (result / numberOfTest).setScale(2);
                                              } 
                                              if(candidate.Skills__c.containsIgnoreCase('salesforse')){
                                                  color = 'skyblue';
                                              }
                                              if(candidate.Skills__c.containsIgnoreCase('mobile')){
                                                  color = 'green';
                                              }
                                              auxPeopleRanked.add(new RankingWrapper(candidate.Name, candidate.Id, candidate.Role__c, candidate.Seniority__c, color, rankingNumber));
                                              
                                          }
            
        }
        
        auxPeopleRanked.sort();
        peopleRanked.addAll(auxPeopleRanked);
        return peopleRanked;
    }
    
    public static void sendMail(Id address, String subject, String body, String signature, String footer) {
        // Create an email message object
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        mail.setTargetObjectId(address);
        system.debug(address);
        mail.saveAsActivity = false;
        mail.setSubject(subject);
        String bodyemail = '<html><head></head><body>' + body +'<div><br/>' + signature +'<div><br/>' + '<footer>' + footer + '</footer></body></html>';
        mail.setHtmlBody(bodyemail);
        
        // Pass this email message to the built-in sendEmail method 
        // of the Messaging class
        Messaging.SendEmailResult[] results = Messaging.sendEmail(
            new Messaging.SingleEmailMessage[] { mail });
        
        // Call a helper method to inspect the returned results
        inspectResults(results);
    }
    
    /**
* @description 
* @param results 
* @return
*/
    private static Boolean inspectResults(Messaging.SendEmailResult[] results) {
        Boolean sendResult = true;
        
        // sendEmail returns an array of result objects.
        // Iterate through the list to inspect results. 
        // In this class, the methods send only one email, 
        // so we should have only one result.
        for (Messaging.SendEmailResult res : results) {
            if (res.isSuccess()) {
                System.debug('Email sent successfully.');
            }
            else {
                sendResult = false;
                System.debug('[Email] The following errors occurred: ' + res.getErrors());                 
            }
        }
        return sendResult;
    }
    
}