src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dev Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PsichometricTestsController.cls
public class PsichometricTestsController {
    
    public List<String> testsUrl = new List<String>();
    public String candidateId = ApexPages.currentPage().getParameters().get('Id');
    public Candidate__c candidate;
    
    public PsichometricTestsController(){
        loadTestsUrl();   
    }
    
    private void loadTestsUrl(){
        testsUrl.add('/sfc/servlet.shepherd/version/download/0681I000000JcSg?asPdf=false&operationContext=CHATTER');
        testsUrl.add('/sfc/servlet.shepherd/version/download/0681I000000Jcbi?asPdf=false&operationContext=CHATTER');
        testsUrl.add('/sfc/servlet.shepherd/version/download/0681I000000Jcbe?asPdf=false&operationContext=CHATTER');
        testsUrl.add('/sfc/servlet.shepherd/version/download/0681I000000JcbY?asPdf=false&operationContext=CHATTER');
        testsUrl.add('/sfc/servlet.shepherd/version/download/0681I000000Jcbd?asPdf=false&operationContext=CHATTER');
        testsUrl.add('/sfc/servlet.shepherd/version/download/0681I000000JcbZ?asPdf=false&operationContext=CHATTER');
    }
    
    public Candidate__c getCandidateInfo(){
        candidate = [SELECT Name, Role__c FROM Candidate__c WHERE Id=:candidateId];
        return candidate;
    }
    
    public String getActualDate(){
        DateTime dt = Date.today();
        String dtStr = dt.format('dd/MM/yyyy');
        return dtStr;
    }
    
    public List<String> getTests(){
        List<Integer> positionsSelected = new List<Integer>();
        List<String> testToShow = new List<String>();
        while(positionsSelected.size() < 3){
            Integer randomPosition = getRandomNumber();
            boolean isOnList = false;
            for(Integer i : positionsSelected){
                if(i == randomPosition){
                    isOnList = true;
                }
            }
            if(isOnList == false){
                positionsSelected.add(randomPosition);
                testToShow.add(testsUrl.get(randomPosition));
            }
        }
        return testToShow;
    }
    
    private Integer getRandomNumber(){
        Double d = math.random() * testsUrl.size();
        return d.intValue();
    }

}