src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dev Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Option__c.object
<CustomObject>
    <fields>
        <fullName>Option_Text__c</fullName>
        <label>Option Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Techincal_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Question</label>
        <referenceTo>Technical_Question__c</referenceTo>
        <relationshipLabel>Option</relationshipLabel>
        <relationshipName>Option</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>anwser__c</fullName>
        <label>Answer</label>
        <picklist>
            <picklistValues>
                <fullName>Correct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Option</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Technical_Question__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Head Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resources Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Technical_Question_Text__c</fullName>
        <label>Technical Question Text</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Technology__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technology</label>
        <referenceTo>Technology__c</referenceTo>
        <relationshipLabel>Technical Questions</relationshipLabel>
        <relationshipName>Technical_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Technical Question</label>
    <nameField>
        <displayFormat>TQ-{0000}</displayFormat>
        <label>Technical Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technical Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Technical_Test__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Technical Tests</relationshipLabel>
        <relationshipName>Technical_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Techincal_Question__c</fullName>
        <label>Techincal Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technology__c</fullName>
        <label>Technology</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Technical Test</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Technical Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technical Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Technology__c.object
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TechnicalControllerTest.cls
@isTest
public class TechnicalControllerTest {
    
    @isTest 
    static void testSearch() {
        Test.startTest();
        //setup
        List<Technology__c> technologies  = new List<Technology__c >();
        Technology__c technology1 = new Technology__c(Name = 'Java');
        Technology__c technology2 = new Technology__c(Name = 'C#');
        technologies.add(technology1);
        technologies.add(technology2);
        insert technologies;
        
        List<Technical_Question__c> technicalQuestions = new List<Technical_Question__c>();
        List<Option__c> options = new List<Option__c>();
        Technical_Question__c technicalQuestions2 = new Technical_Question__c(Technical_Question_Text__c  ='Something', Role__c = 'QA', Seniority__c = 'Junior', Technology__c = technology1.Id);
        technicalQuestions.add(technicalQuestions2);
        
        for(Integer i = 1; i <= 10; i++){
            Technical_Question__c technicalQuestions1 = new Technical_Question__c(Technical_Question_Text__c  ='Something' + i, Role__c = 'Developer', Seniority__c = 'Senior', Technology__c = technology2.Id);
            technicalQuestions.add(technicalQuestions1);
        }
        
        insert technicalQuestions;
        
        for(Technical_Question__c tq : technicalQuestions){
            Option__c option1 = new Option__c(Techincal_Question__c = tq.Id, anwser__c = 'Correct', Option_Text__c = '1' );
            Option__c option2 = new Option__c(Techincal_Question__c  = tq.Id, anwser__c = 'Incorrect', Option_Text__c = '2' );
            Option__c option3 = new Option__c(Techincal_Question__c = tq.Id, anwser__c = 'Incorrect', Option_Text__c = '3' );
            Option__c option4 = new Option__c(Techincal_Question__c  = tq.Id, anwser__c = 'Incorrect', Option_Text__c = '4' );
            
            options.add(option1);
            options.add(option2);
            options.add(option3);
            options.add(option4);
        }
        
        insert options;
        
        List<Candidate__c> candidates = new List<Candidate__c>();
        Candidate__c candidate = new Candidate__c(Role__c ='QA', CI__c = 11111111, Seniority__c = 'Junior', Skills__c = 'Something');
        Candidate__c candidate2 = new Candidate__c(Role__c ='Developer', CI__c = 22222222, Seniority__c = 'Junior', Skills__c = 'Something');
        Candidate__c candidate3 = new Candidate__c(Role__c ='Developer', CI__c = 33333333, Seniority__c = 'Junior', Skills__c = 'Something');
        candidates.add(candidate);
        candidates.add(candidate2);
        candidates.add(candidate3);
        insert candidates;
        
        
        //end setup
        Test.stopTest();
        
        TechnicalController controller = new TechnicalController();
        controller.getRoleItems();
        controller.getSeniorityItems();
        controller.getTechnologyItems();
        controller.ciCandidate = 11111111;
        controller.role = 'Developer';
        controller.seniority = 'Senior';
    	controller.technology = 'C#';
        
        controller.start();
		System.assertEquals(JSUtils.NUMBER_OF_QUESTIONS, controller.questions.size());
        controller.Next();
        controller.Previous();
        System.assertEquals(true, controller.getDisablePrevious());
        System.assertEquals(false, controller.getDisableNext());
        controller.checkResults();
        
        List<Technical_Test__c> technicalTest = [SELECT Id FROM Technical_Test__c];
        
        System.assertEquals(1, technicalTest.size());
        
        controller.otherTest();
        System.assertEquals('display: none', controller.showHideName);
        
    }

}