src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Workplace__c</fullName>
        <label>Actual Workplace</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dev Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PsichometricTestsControllerTest.cls
@isTest
public class PsichometricTestsControllerTest {
    
    @testSetup
    static void setupData(){
        Candidate__c c = new Candidate__c();
        c.Actual_Workplace__c = 'Test';
        c.CI__c = 11111111;
        c.Name = 'Test Candidate';
        c.Role__c = 'Developer';
        c.Seniority__c = 'Junior';
        c.Skills__c = 'Test Skills';
        insert c;
        
    }
    
    @isTest
    static void testGetCandidateInfo(){
        Candidate__c c = [SELECT Id FROM Candidate__c WHERE Name = 'Test Candidate'];
        
        Test.startTest();
        PsichometricTestsController controller = new PsichometricTestsController();
        controller.candidateId = c.Id;
        Candidate__c fromServer = controller.getCandidateInfo();
        Test.stopTest();
        
        System.assertEquals('Test Candidate', fromServer.Name);
    }
    
    @isTest
    static void testGetActualDate(){
        Test.startTest();
        PsichometricTestsController controller = new PsichometricTestsController();
        String dateFromServer = controller.getActualDate();
        Test.stopTest();
        
        DateTime dt = Date.today();
        String dtStr = dt.format('dd/MM/yyyy');
        
        System.assertEquals(dtStr, dateFromServer);
    }
    
    @isTest
    static void testGetTests(){
        Test.startTest();
        PsichometricTestsController controller = new PsichometricTestsController();
        List<String> tests = controller.getTests();
        Test.stopTest();
        
        System.assertEquals(3, tests.size());
    }
    
    
    

}