src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Workplace__c</fullName>
        <label>Actual Workplace</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Languages__c</fullName>
        <label>Languages</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dev Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CompanyStartDate__c</fullName>
        <label>Company Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DepartureDate__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DepartureReason__c</fullName>
        <label>Departure Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Quit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fired</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Languages__c</fullName>
        <label>Languages</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Torre 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Torre 2</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Head Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resources Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change: Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change: Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Employee</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Team</relationshipLabel>
        <relationshipName>Project_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{000000}</displayFormat>
        <label>PTM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmployeeController.cls
public with sharing class EmployeeController {
    
    @AuraEnabled
    public static void updateTerminateEmployee(String empId, String option){
        Employee__c emp = [SELECT Id, Name, DepartureDate__c, DepartureReason__c, Status__c FROM Employee__c WHERE Id=:empId];
        if(emp.Status__c != 'Former Employee'){
        	emp.DepartureDate__c = Date.Today();
           	emp.DepartureReason__c = option;
            emp.Name = emp.Name + ' (Former Employee)';
            emp.Status__c = 'Former Employee';
            unlinkEmployeeFromProject(emp);
            update emp;
        }
    }
    
    private static void unlinkEmployeeFromProject(Employee__c emp){
        
        List<Project_Team_Member__c> ptmRecords = [SELECT Id, Employee__r.Id, Project__r.Id FROM Project_Team_Member__c WHERE Employee__r.Id =: emp.Id];
        try{
            delete ptmRecords;
        }catch(DmlException e){
            System.debug('Unknown error while deleting Project_Team_Member__c record.');
        }
        
    }
    
    @AuraEnabled
    public static Integer convertCandidateToEmployee(String candidateId, String startDate, String location, String status, String project){
        //returns: 0 - all good, 1 - error, 2 - already converted
        Candidate__c candidate = [SELECT Name, Birthdate__c, CI__c, Role__c, Seniority__c, Skills__c, Languages__c FROM Candidate__c WHERE Id =: candidateId];
        if(candidate.Name.contains('- (Converted to Employee)')) return 2;
        Employee__c newEmployee = new Employee__c();
        newEmployee.Name = candidate.Name;
        newEmployee.Birthdate__c = candidate.Birthdate__c;
        newEmployee.CI__c = candidate.CI__c;
        newEmployee.Role__c = candidate.Role__c;
        newEmployee.Seniority__c = candidate.Seniority__c;
        newEmployee.Skills__c = candidate.Skills__c;
        newEmployee.CompanyStartDate__c = convertDate(startDate);
        newEmployee.Location__c = location;
        newEmployee.Status__c = status;
        newEmployee.Languages__c = candidate.Languages__c;
        
        Database.SaveResult insRslt = Database.insert(newEmployee);
        if(insRslt.isSuccess()){
            candidate.Name = candidate.Name + ' - (Converted to Employee)';
            candidate.Actual_Workplace__c = 'Altimetrik';
            update candidate;
            if(project != null){
                createNewPTM(project, newEmployee);
            }
            return 0;
        }else{
            System.debug('Error while converting a Candidate to Employee');
            return 1;
        }
    }
    
    private static void createNewPTM(String projectName, Employee__c employee){
        Project__c project = [SELECT Id FROM Project__c WHERE Name =: projectName];
        
        Project_Team_Member__c ptm = new Project_Team_Member__c();
        ptm.Employee__c = employee.Id;
        ptm.Project__c = project.Id;
        ptm.Role__c = employee.Role__c;
        insert ptm;
    }
    
    @AuraEnabled
    public static List<Project__c> getProjects(){
        List<Project__c> projects = [SELECT Id, Name FROM Project__c ORDER BY Name];
        return projects;
    }
    
    private static Date convertDate(String dateString){
        return Date.valueOf(dateString);
    }

}