src/objects/EmployeeContract__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FullName__c</fullName>
        <label>Full Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HoursOfWork__c</fullName>
        <label>Hours of Work</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JobTitle__c</fullName>
        <label>Job Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProbationaryPeriod__c</fullName>
        <label>Probationary Period</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Employee Contract</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractCreationController.cls
public class ContractCreationController {
    public String contratId = ApexPages.currentPage().getParameters().get('Id');
    public EmployeeContract__c contract = new EmployeeContract__c();
    
    
    public EmployeeContract__c getEmployeeContractInfo(){
        
        contract = [SELECT Id, Address__c, CI__c, FullName__c, Description__c, HoursOfWork__c , JobTitle__c, ProbationaryPeriod__c, Salary__c, StartDate__c  
                    FROM EmployeeContract__c WHERE Id=:contratId];
        return contract;
    }

}