src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Head Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resources Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <type>TextArea</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TechnicalSkillsControllerTest.cls
@isTest
public class TechnicalSkillsControllerTest {
    @isTest 
    static void testSearchSkill() {
        Test.startTest();
        //setup
        List<Employee__c> employees = new List<Employee__c>();
        Employee__c employee = new Employee__c(Role__c ='Head Manager', CI__c = 11111111, Skills__c  = 'HTML5');
        Employee__c employee2 = new Employee__c(Role__c ='Head Manager', CI__c = 22222222, Skills__c  = 'HTML5');
        employees.add(employee);
        employees.add(employee2);
        insert employees;
        //end setup
        Test.stopTest();
        
        TechnicalSkillsController controller = new TechnicalSkillsController();
        string a = controller.showHideTable;
        controller.searchSkill = 'HTML5';
        controller.searchSkill();
        
        System.assertEquals(2, controller.employees.size());
        System.assertEquals(false, controller.getEmpty());
        System.assertEquals(true, controller.getDisableNext());
        System.assertEquals(true, controller.getDisablePrevious());
        controller.Next();
        controller.Previous();
        controller.clear();
        
        System.assertEquals(0, controller.employees.size());
        System.assertEquals(true, controller.getEmpty());
        
        
    }

}