src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CompanyStartDate__c</fullName>
        <label>Company Start Date</label>
        <type>Date</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EmployeeContract__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employees Contracts</relationshipLabel>
        <relationshipName>Employees_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FullName__c</fullName>
        <label>Full Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HoursOfWork__c</fullName>
        <label>Hours of Work</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JobTitle__c</fullName>
        <label>Job Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProbationaryPeriod__c</fullName>
        <label>Probationary Period</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Employee Contract</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractsController.cls
public class ContractsController { 
    
    public String showHide { get{
        return 'slds-hide';
    } set;}
    public String name {get;set;}
    public Integer employee {get;set;}
    public Decimal ci {get;set;}
    public String address {get;set;}
    public Date startDate{ get{
        if(startDate==null){
            startDate = Date.today();
        }
        return startDate;
    } set;}
    public String jobTitle {get;set;}
    public String description {get;set;}
    public Decimal hoursOfWork {get;set;}
    public Decimal probationaryPeriod {get;set;}
    public Decimal salary {get;set;}
    public Id employeeId;
    
    
    public void saveContract(){
        if(name != '' && address != '' ){
            EmployeeContract__c contract = new EmployeeContract__c();
            contract.CI__c = ci;
            contract.FullName__c  = name;
            contract.StartDate__c  = startDate;
            contract.Description__c =  description;
            contract.Address__c  = address;
            contract.JobTitle__c  = jobTitle;
            contract.HoursOfWork__c  = hoursOfWork;
            contract.ProbationaryPeriod__c  = probationaryPeriod;
            contract.Salary__c  = salary;
            contract.Employee__c = employeeId;
            insert contract;
            
        }
    }
    
    public void searchEmployee(){
        if(employee != null && employee > 0){
            List<Employee__c> employeeData = JSUtils.getEmployee(employee);
            system.debug('employeeData');
            system.debug(employeeData);
            if(employeeData.size() > 0){
                ci = employeeData[0].CI__c;
                address = employeeData[0].Address__c;
                startDate = employeeData[0].CompanyStartDate__c;
                name = employeeData[0].Name;
                employeeId = employeeData[0].Id;
                hoursOfWork  = 9;
                probationaryPeriod = 3;
                salary = 25000;
            }
        }
        
        
    }
    
}