src/objects/EmployeeContract__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FullName__c</fullName>
        <label>Full Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Employee Contract</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractCreationControllerTest.cls
@isTest
public class ContractCreationControllerTest {
    
    @isTest 
    static void testCreateContract() {
        Test.startTest();
        //setup
        DateTime dT = System.now();
        Date myDate = date.newinstance(dT.year(), dT.month(), dT.day());
        EmployeeContract__c employeeContract = new EmployeeContract__c(Address__c = 'Something', CI__c = 22222222, FullName__c = 'Taylor Swift', StartDate__c = myDate);
        insert employeeContract;
        //end setup
        
        ContractCreationController controller = new ContractCreationController();
        controller.contratId = employeeContract.Id;
        controller.getEmployeeContractInfo();
        Test.stopTest();
        
        System.assertEquals('Taylor Swift', controller.contract.FullName__c);
    }

}