src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Head Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resources Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EmployeeContract__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI__c</fullName>
        <label>CI</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employees Contracts</relationshipLabel>
        <relationshipName>Employees_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee Contract</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractsControllerTest.cls
@isTest
public class ContractsControllerTest {
    
    @isTest 
    static void testSearch() {
        Test.startTest();
        //setup
        List<Employee__c> employees = new List<Employee__c>();
        Employee__c employee = new Employee__c(Role__c ='Head Manager', CI__c = 11111111);
        Employee__c employee2 = new Employee__c(Role__c ='Head Manager', CI__c = 22222222);
        employees.add(employee);
        employees.add(employee2);
        insert employees;
        //end setup
        Test.stopTest();
        
        ContractsController controller = new ContractsController();
        string a = controller.showHide;
        controller.employee = 11111111;
        controller.searchEmployee();
        
        System.assertEquals(employee.CI__c, controller.ci);
    }
    
     @isTest 
    static void testSave() {
        Test.startTest();
        //setup
        List<Employee__c> employees = new List<Employee__c>();
        Employee__c employee = new Employee__c(Role__c ='Head Manager', CI__c = 11111111, Address__c = 'AAA');
        Employee__c employee2 = new Employee__c(Role__c ='Head Manager', CI__c = 22222222, Address__c = 'AAA');
        employees.add(employee);
        employees.add(employee2);
        insert employees;
        //end setup
        //
        ContractsController controller = new ContractsController();
        controller.employee = 22222222;
        controller.searchEmployee();
        controller.name = 'Ayessa';
        controller.jobTitle = 'Designer';
        controller.description = 'Something';
        controller.hoursOfWork = 9;
        controller.saveContract();
        
        Test.stopTest();
        
        List<EmployeeContract__c> contracts = [SELECT Id FROM EmployeeContract__c];
        
        System.assertEquals(1, contracts.size());
    }
    
}